### ISSUE TITLE
material-ripple takes entire screen

### ISSUE THREAD

**Issue by vfede** [dart-lang/angular2_components#22]
i'm setting up a showcase page based on the project showcase. I defined a simple custom card component, but adding a material-ripple to it, it takes the entire visibile content above the fold (if the page is scrollable, the ripple doesn't extend to the part below the fold).
this is a screenshot while clicking on the page lower right:

![image](https://cloud.githubusercontent.com/assets/1517314/20483913/eade7994-aff4-11e6-99ae-7daef230c7a4.png)

```html
<div class="simple-card">
  <img class="simple-card__image"
       [src]="imageUrl"/>
  <p class="simple-card__text">
    {{text}}
  </p>
  <material-ripple></material-ripple>
</div>
```
```css
.simple-card {
    display: flex;
    align-items: center;
    height: 56px;
    min-width: 288px;
    max-width: 368px;
    background-color: #fff;
    border-radius: 2px;
    box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.12), 0 1px 5px 0 rgba(0, 0, 0, 0.2);
}
```
```dart
import 'package:angular2/core.dart';
import 'package:angular2_components/angular2_components.dart';

@Component(
    selector: 'qui-simple-card',
    styleUrls: const ['qui_simple_card.css'],
    templateUrl: 'qui_simple_card.html',
    directives: const [
      materialDirectives,
      materialInputDirectives
    ],
    providers: const [materialProviders])
class QuiSimpleCardComponent {
  @Input('img-src')
  String imageUrl;

  @Input()
  String text;
}
```

I expected the ripple to be confined inside my card borders. Am I doing something wrong or is this a bug?
using latest dart 1.20.1 and angular2 2.0
